# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='activation_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='activation_expires',
            new_name='keytime',
        ),
    ]
