# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20161123_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
